### PR TITLE
resolve api and add usehistory and useParams

### PR DESCRIPTION
**Pull request by Erriep**

### CODE REVIEW

**Comment by Erriep** [comment]
resolve api and add usehistory and useParams

**Review by Hacene010 — DISMISSED** [review]

**Comment by LoicBrassart** [comment]
Ongoing conflicts, please fix ;-)

**Comment by LoicBrassart** [comment]
Please fix conflicts

**Review by Hacene010 — APPROVED** [review]

**Review by LoicBrassart — APPROVED** [review]
Saw no Evil

**Pull request merged**
